"""How Alembic reaches the database, and what autogenerate compares against.

Three decisions worth knowing before editing this file.

*The URL is not in `alembic.ini`.* It comes from `DatabaseSettings.from_env()`,
the same resolution the async repositories use, so a developer, docker-compose,
CI and the test suite cannot end up pointing at different databases — and no
credential is ever committed.

*A caller may supply its own connection.* `config.attributes["connection"]` is
Alembic's documented hook for running migrations programmatically; the test suite
uses it to migrate inside a transaction it controls, which is how "build the
schema from scratch" is a test rather than a manual step.

*The PostGIS extension's own objects are filtered out.* `CREATE EXTENSION postgis`
puts `spatial_ref_sys` and several views in `public`. They are not in
`Base.metadata`, so an unfiltered autogenerate would confidently propose to drop
them.
"""
from logging.config import fileConfig

from alembic import context
from sqlalchemy import Connection, pool
from sqlalchemy.sql.schema import SchemaItem

from backend.app.core.settings import DatabaseSettings
from backend.app.infrastructure.database import models  # noqa: F401 - registers tables
from backend.app.infrastructure.database.base import Base, type_bound_check_constraint_names
from backend.app.infrastructure.database.engine import create_sync_database_engine
from backend.app.infrastructure.database.types import (
    is_postgis_owned,
    register_geography_reflection,
)

config = context.config

# Before anything reflects the database. Autogenerate compares a reflected column
# against the mapped one, and an unregistered `geography` reflects as `NullType` —
# which compares equal to everything and would hide a change to a point column.
register_geography_reflection()

# `configure_logger` is the escape hatch for programmatic runs: `fileConfig`
# rewrites the root logger, which would tear down pytest's capture for every test
# that migrates. Guarded rather than removed, because the INFO line telling a
# developer which revision is running is worth having on the command line.
if config.attributes.get("configure_logger", True) and config.config_file_name:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# Importing `models` above is what fills this in — the metadata is empty until the
# mapped classes are defined, and autogenerate would read that as "drop
# everything".
target_metadata = Base.metadata

# Computed once, after the import above, for the reason spelled out on the
# function: without this filter every new autogenerated revision would propose to
# drop the CHECK constraint behind each enum column.
_TYPE_BOUND_CHECKS = type_bound_check_constraint_names(target_metadata)


def include_object(object_: SchemaItem, name: str | None, type_: str,
                   reflected: bool, compare_to: SchemaItem | None) -> bool:
    """Decide whether autogenerate is allowed to have an opinion about an object.

    Two exclusions, both of things this schema does not own: PostGIS's tables, and
    the CHECK constraints that belong to a column's `Enum` type.
    """
    if is_postgis_owned(object_, name):
        return False
    return not (type_ == "check_constraint" and name in _TYPE_BOUND_CHECKS)


# `compare_type` catches a column whose Python type changed without a migration —
# the drift this schema is most likely to grow, since types come from
# `type_annotation_map`. `compare_server_default` stays off: PostgreSQL normalizes
# a default such as `'{}'::jsonb` on the way in, and the resulting cosmetic diffs
# would train the reader to ignore autogenerate output. Both `configure` calls
# below repeat these three options rather than sharing a dict, because Alembic's
# signature is precisely typed and `**kwargs` would erase it.


def run_migrations_offline() -> None:
    """Emit the DDL as SQL instead of running it (`alembic upgrade head --sql`).

    Kept working because it is how a migration gets reviewed before it touches
    anything that matters: a deployment can read the statements first.
    """
    context.configure(url=DatabaseSettings.from_env().url, literal_binds=True,
                      dialect_opts={"paramstyle": "named"},
                      target_metadata=target_metadata, include_object=include_object,
                      compare_type=True)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations(connection: Connection) -> None:
    """Run every pending revision on an open connection.

    One transaction for the whole upgrade, which is Alembic's default and the
    behaviour to keep: a failed revision leaves the schema and `alembic_version`
    exactly as they were, instead of half-migrated.
    """
    context.configure(connection=connection, target_metadata=target_metadata,
                      include_object=include_object, compare_type=True)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Connect — or borrow the caller's connection — and migrate."""
    borrowed = config.attributes.get("connection", None)
    if isinstance(borrowed, Connection):
        run_migrations(borrowed)
        return

    # `NullPool` because this process runs one upgrade and exits; a pool would
    # only add a connection that has to be reaped.
    engine = create_sync_database_engine(DatabaseSettings.from_env(),
                                        poolclass=pool.NullPool)
    try:
        with engine.connect() as connection:
            run_migrations(connection)
    finally:
        engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
