"""The one place the backup layer shells out to libpq, and the rules it runs under (§45).

`pg_dump`, `pg_restore` and `psql` are the production backup tooling §45 names, and they are genuine
subprocess work with a genuine way to go wrong — a credential leaked onto the command line. So, like
the LLM CLI runner (`backend/app/llm/providers/cli_runner.py`), it is done once, here, under
explicit rules:

- **Explicit argv, never a shell.** `subprocess.run([...])`, not a shell string, so a value can
  never be reinterpreted as a shell metacharacter (docs/ENGINEERING_STANDARDS.md §Security).
- **The password travels in the environment, never in argv.** The child's environment is the parent
  environment plus the target's libpq variables (`PGPASSWORD` among them); no connection argument
  carries the credential, so `ps` and a process listing show only `host:port/db`.
- **A failure is typed, not a traceback, and credential-free.** A non-zero exit becomes a
  `BackupToolError` carrying the tool, the redacted target and the tool's stderr — which cannot hold
  the password, because the password was never on the line the tool echoes.

The runner knows nothing about *why* a dump is taken or *where* it is verified; it dumps, restores,
creates and drops on command. The `BackupService` above it owns the orchestration and the safety
guards. A `PgToolRunner` protocol lets that service be driven by a fake in unit tests, while the
`SubprocessPgToolRunner` here is what a CLI and the real restore smoke test use.
"""
from __future__ import annotations

import re
import subprocess
from os import environ
from pathlib import Path
from typing import Protocol

from backend.app.backup.connection import PostgresConnectionParams
from backend.app.backup.errors import BackupToolError

# A scratch database name is generated by us (a uuid-derived suffix), never user-supplied, but it is
# still validated against this before it reaches a `CREATE DATABASE`/`DROP DATABASE` statement — a
# belt-and-braces guard so an identifier can never carry anything but letters, digits, underscore.
_SAFE_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# The maintenance database `createdb`/`dropdb` connect to, because you cannot create or drop a
# database while connected to it. Every PostgreSQL cluster has it.
_MAINTENANCE_DATABASE = "postgres"


def _require_identifier(name: str) -> str:
    """Return `name` if it is a bare SQL identifier, else refuse — no injection into DDL."""
    if not _SAFE_IDENTIFIER.match(name):
        raise ValueError(f"unsafe database identifier: {name!r}")
    return name


class PgToolRunner(Protocol):
    """What the backup service needs from the libpq tools — dump, restore, and scratch-DB lifecycle.

    A protocol so the service is testable with a fake: unit tests assert the *orchestration* (order,
    guards, the credential-free report) without a live PostgreSQL, and the real
    `SubprocessPgToolRunner` is exercised by the isolated restore smoke test (§74) where a database
    and the binaries are available.
    """

    def dump(self, source: PostgresConnectionParams, dump_path: Path) -> None:
        """Write a custom-format dump of `source` to `dump_path`."""
        ...

    def restore(self, target: PostgresConnectionParams, dump_path: Path) -> None:
        """Restore `dump_path` into `target` (an already-created, empty database)."""
        ...

    def create_database(self, admin: PostgresConnectionParams, name: str) -> None:
        """Create database `name`, connecting through `admin`'s maintenance connection."""
        ...

    def drop_database(self, admin: PostgresConnectionParams, name: str) -> None:
        """Drop database `name` if it exists, connecting through `admin`."""
        ...


class SubprocessPgToolRunner:
    """Runs the libpq tools with explicit argv, the password in the environment, and typed failures.

    Stateless and reusable. The three binary paths come from `BackupSettings` (bare names resolved
    on `PATH` by default, overridable to pin a client version). `timeout_seconds` bounds every call
    so a wedged tool cannot hang an operator command or a CI job forever.
    """

    def __init__(self, *, pg_dump_path: str, pg_restore_path: str, psql_path: str,
                 timeout_seconds: float = 3600.0) -> None:
        self._pg_dump = pg_dump_path
        self._pg_restore = pg_restore_path
        self._psql = psql_path
        self._timeout = timeout_seconds

    def _run(self, tool: str, argv: list[str], params: PostgresConnectionParams) -> None:
        """Run one tool, passing the connection through the environment, and type any failure."""
        child_env = dict(environ)
        child_env.update(params.libpq_env())
        try:
            completed = subprocess.run(
                argv, env=child_env, capture_output=True, text=True,
                timeout=self._timeout, check=False)
        except FileNotFoundError as exc:
            raise BackupToolError(
                tool, params.redacted, returncode=127,
                stderr=f"{tool} is not installed or not on PATH") from exc
        except subprocess.TimeoutExpired as exc:
            raise BackupToolError(
                tool, params.redacted, returncode=124,
                stderr=f"{tool} timed out after {self._timeout:.0f}s") from exc
        if completed.returncode != 0:
            raise BackupToolError(
                tool, params.redacted, returncode=completed.returncode,
                stderr=completed.stderr)

    def dump(self, source: PostgresConnectionParams, dump_path: Path) -> None:
        # Custom format (`-Fc`): compressed, and the only format `pg_restore` can reorder and
        # selectively load. `--no-owner`/`--no-privileges` keep the dump portable to a cluster whose
        # roles differ. The connection is entirely in the environment; only the output path is argv.
        self._run(self._pg_dump, [
            self._pg_dump, "--format=custom", "--no-owner", "--no-privileges",
            "--file", str(dump_path)], source)

    def restore(self, target: PostgresConnectionParams, dump_path: Path) -> None:
        # Restores into an empty database, so no `--clean` is needed. `--no-owner`/`--no-privileges`
        # match the dump; errors are left non-fatal (a benign notice on an extension must not abort)
        # because the real proof is the post-restore schema/version/record check the service runs.
        self._run(self._pg_restore, [
            self._pg_restore, "--no-owner", "--no-privileges",
            "--dbname", target.database, str(dump_path)], target)

    def create_database(self, admin: PostgresConnectionParams, name: str) -> None:
        safe = _require_identifier(name)
        self._run(self._psql, [
            self._psql, "--no-psqlrc", "--set", "ON_ERROR_STOP=1",
            "--command", f'CREATE DATABASE "{safe}"'],
            admin.for_database(_MAINTENANCE_DATABASE))

    def drop_database(self, admin: PostgresConnectionParams, name: str) -> None:
        safe = _require_identifier(name)
        # `WITH (FORCE)` (PostgreSQL 13+) terminates any lingering connection so the scratch DB
        # can always be reclaimed; `IF EXISTS` makes teardown idempotent after a partial run.
        self._run(self._psql, [
            self._psql, "--no-psqlrc", "--set", "ON_ERROR_STOP=1",
            "--command", f'DROP DATABASE IF EXISTS "{safe}" WITH (FORCE)'],
            admin.for_database(_MAINTENANCE_DATABASE))
